#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Ports massar-ds/massar.css into src/massar-ds-crm.ts, scoped to .ds6.

The new design system replaces the tokens, the type scale and the component
vocabulary wholesale. Its :root would repaint all 26 screens at once, and the
other 25 still carry the old class structure — new tokens under old structure
is not a half-finished redesign, it is a broken page. So every selector is
confined to a .ds6 subtree and a screen opts in by wrapping its body in that
class. The scoping comes out when the last screen is ported.

Run after any change to massar-ds/massar.css:

    python3 scripts/port-ds.py
"""
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", "..", "massar-ds", "massar.css"))
OUT = os.path.normpath(os.path.join(HERE, "..", "src", "massar-ds-crm.ts"))

SCOPE = ".ds6"


def split_rules(s):
    """Flat split into (selector, body). @-blocks come back with their body intact."""
    out, i, n = [], 0, len(s)
    while i < n:
        j = s.find("{", i)
        if j < 0:
            break
        sel = s[i:j].strip()
        depth, k = 1, j + 1
        while k < n and depth:
            if s[k] == "{":
                depth += 1
            elif s[k] == "}":
                depth -= 1
            k += 1
        out.append((sel, s[j + 1:k - 1]))
        i = k
    return out


COMMENT = re.compile(r"/\*.*?\*/", re.S)


def scope_sel(sel):
    """Scope a selector, leaving any comment that precedes it alone.

    split_rules hands back everything between the previous rule and the brace, so a comment above
    a rule arrives as part of "sel". Splitting that on commas — which is how a selector list is
    split — tore a comment containing a comma into fragments and prefixed each one, leaving the
    real selector UNSCOPED at the end. The result leaked .hds-ind into every screen in the app
    and was invisible in the source. Comments carry the reasoning, so they are preserved verbatim
    and only what follows them is treated as a selector.
    """
    lead = ""
    m = list(COMMENT.finditer(sel))
    if m:
        cut = m[-1].end()
        lead, sel = sel[:cut], sel[cut:]
    parts = []
    for p in [x.strip() for x in sel.split(",")]:
        if not p:
            continue
        if p == ":root":
            # Tokens go on :root UNSCOPED. They are --m-* prefixed, so they collide with
            # nothing in the old system, and the shell (one shared rail and top bar, outside
            # any screen's subtree) has to be able to read them. Only the component RULES are
            # scoped; a variable that is merely declared paints nothing on its own.
            parts.append(":root")
        elif p in ("body", "html"):
            parts.append(SCOPE)
        elif p.startswith(SCOPE):
            parts.append(p)
        else:
            parts.append(SCOPE + " " + p)
    return lead + ", ".join(parts)


def scope(css):
    out = []
    for sel, body in split_rules(css):
        if sel.startswith("@media") or sel.startswith("@supports"):
            inner = "".join("%s{%s}" % (scope_sel(s2), b2)
                            for s2, b2 in split_rules(body))
            out.append("%s{%s}" % (sel, inner))
        elif sel.startswith("@"):
            # keyframes, font-face, import: no selectors to scope.
            out.append("%s{%s}" % (sel, body))
        else:
            out.append("%s{%s}" % (scope_sel(sel), body))
    return "\n".join(out)


HEADER = u"""// massar-ds-crm.ts — the new design system, scoped to the screens that have been ported.
//
// GENERATED by scripts/port-ds.py from ../../massar-ds/massar.css. Do not edit by hand:
// edit the source and re-run. massar-ds/gen.py generates that source in turn.
//
// WHY SCOPED. This system replaces the tokens, the type scale and the component vocabulary
// wholesale: its :root would repaint all 26 screens at once, and the other 25 still carry the old
// class structure. New tokens under old structure is not a half-finished redesign, it is a broken
// page. So every selector here is confined to a .ds6 subtree. A screen opts in by wrapping its
// body in that class; nothing else moves. The scoping comes out when the last screen is ported.
//
// (No backticks anywhere below, including in comments: this is one template literal.)

export const MASSAR_DS_CSS = `
"""


def main():
    if not os.path.exists(SRC):
        sys.exit("source stylesheet not found: %s" % SRC)
    css = io.open(SRC, encoding="utf-8").read()
    scoped = scope(css)

    # The gate forbids a backtick inside a *_CSS literal; a stray one would
    # terminate the string and turn the rest of the file into TypeScript.
    leaks = []
    for sel, _body in split_rules(scoped):
        bare = COMMENT.sub("", sel).strip()
        if not bare or bare.startswith("@"):
            continue
        for part in bare.split(","):
            part = part.strip()
            if part and not part.startswith(SCOPE) and part != ":root":
                leaks.append(part)
    if leaks:
        sys.exit("refusing to write: %d rule(s) escaped the %s scope and would paint the whole "
                 "app: %s" % (len(leaks), SCOPE, ", ".join(leaks[:6])))

    if "`" in scoped:
        sys.exit("refusing to write: backtick in the scoped CSS")
    if "${" in scoped:
        sys.exit("refusing to write: template interpolation in the scoped CSS")

    io.open(OUT, "w", encoding="utf-8").write(HEADER + scoped + u"\n`;\n")
    print("wrote %s (%d bytes of CSS)" % (os.path.relpath(OUT), len(scoped)))


if __name__ == "__main__":
    main()
