// massar-ds-crm.ts — the new design system, scoped to the screens that have been ported.
//
// GENERATED by scripts/port-ds.py from ../../massar-ds/massar.css. Do not edit by hand:
// edit the source and re-run. massar-ds/gen.py generates that source in turn.
//
// WHY SCOPED. This system replaces the tokens, the type scale and the component vocabulary
// wholesale: its :root would repaint all 26 screens at once, and the other 25 still carry the old
// class structure. New tokens under old structure is not a half-finished redesign, it is a broken
// page. So every selector here is confined to a .ds6 subtree. A screen opts in by wrapping its
// body in that class; nothing else moves. The scoping comes out when the last screen is ported.
//
// (No backticks anywhere below, including in comments: this is one template literal.)

export const MASSAR_DS_CSS = `
.ds6{
  
  --m-page: #F6F7F5;
  --m-paper: #FFFFFF;
  --m-sunk: #EEF1EE;
  --m-line: #E3E7E3;
  --m-line-2: #CDD4CE;
  --m-dot: #D9DFDA;

  --m-ink: #17201F;
  --m-ink-2: #46504D;
  --m-mut: #646D69;
  --m-faint: #646D69;

  --m-ac: #245BD6;
  --m-ac-deep: #1947AF;
  --m-ac-dim: #EEF3FF;
  --m-ac-line: #BCCDF7;

  --m-ok: #17603D;
  --m-ok-dim: #EDF6F0;
  --m-ok-line: #BEDBC8;
  --m-warn: #8A4B08;
  --m-warn-dim: #FFF4E5;
  --m-warn-line: #E8CFAB;
  --m-bad: #B42318;
  --m-bad-dim: #FEF0ED;
  --m-bad-line: #F1C5BE;
  --m-idle: #646D69;
  --m-idle-dim: #EEF1EE;
  --m-idle-line: #CDD4CE;

  
  --m-vi: var(--m-ac);
  --m-vi-dim: var(--m-ac-dim);

  
  --m-t-micro: 13px;
  --m-t-cap: 13px;
  --m-t-body: 15px;
  --m-t-sub: 15px;
  --m-t-h: 20px;
  --m-t-fig: 28px;
  --m-t-display: 28px;
  --m-t-hero: 72px;

  --m-leading-meta: 22px;
  --m-leading-body: 26px;
  --m-leading-section: 32px;
  --m-leading-title: 44px;
  --m-leading-figure: 40px;
  --m-leading-hero: 80px;

  --m-tracking-text: 0;
  --m-tracking-figure: -0.02em;
  --m-tracking-hero: -0.035em;

  
  --m-1: 4px;
  --m-2: 8px;
  --m-3: 12px;
  --m-4: 16px;
  --m-5: 24px;
  --m-6: 32px;
  --m-7: 48px;

  --m-r-chip: 999px;
  --m-r-ctl: 10px;
  --m-r-card: 16px;
  --m-r-band: 20px;

  --m-hair: 0 0 0 1px var(--m-line);
  --m-low: 0 1px 2px rgb(0 0 0 / 3%);
  --m-soft: 0 2px 8px rgb(0 0 0 / 3%);
  --m-lift: 0 8px 24px rgb(0 0 0 / 10%);
  --m-focus: 0 0 0 3px var(--m-ac-line);

  --m-ease: cubic-bezier(.16, 1, .3, 1);
  --m-move: var(--m-ease);
  --m-press: 100ms;
  --m-swap: 120ms;
  --m-in: 180ms;
  --m-out: 120ms;
}
.ds6 *, .ds6 *::before, .ds6 *::after{box-sizing:border-box}
.ds6, .ds6{margin:0}
.ds6{
  font-family: Cairo, system-ui, sans-serif;
  background: var(--m-page);
  color: var(--m-ink-2);
  direction: rtl;
  font-size: var(--m-t-body);
  line-height: var(--m-leading-body);
  -webkit-font-smoothing:antialiased;
  letter-spacing: 0;
  font-variant-numeric: lining-nums tabular-nums;
}
@media (prefers-reduced-motion:reduce){.ds6 *, .ds6 *::before, .ds6 *::after{animation-duration:1ms!important;transition-duration:1ms!important}}
.ds6 .m-n{
  font-variant-numeric: lining-nums tabular-nums;
  font-feature-settings: "lnum" 1, "tnum" 1;
  direction: ltr;
  unicode-bidi: isolate;
  display: inline-block;
}
.ds6 .m-shell{
  display:flex;
  min-block-size: 100dvh;
}
.ds6 .m-side{
  inline-size: 224px;
  flex:0 0 auto;
  background:var(--m-paper);
  border-inline-start: 0;
  display:flex;
  flex-direction:column;
  position:sticky;
  inset-block-start:0;
  block-size: 100dvh;
  overflow:hidden;
  transition:inline-size var(--m-in) var(--m-ease);
  border-inline-end: 1px solid var(--m-line);
  transition-duration: var(--m-in);
}
.ds6 .m-side[data-collapsed]{
  inline-size: 68px;
  transition-duration: var(--m-out);
}
.ds6 .m-side__b{display:flex;align-items:center;gap:var(--m-2);padding:var(--m-4) var(--m-3) var(--m-2);
           white-space:nowrap}
.ds6 .m-side__logo{
  inline-size:28px;
  block-size:28px;
  border-radius:9px;
  flex:0 0 auto;
  display:grid;
  place-items:center;
  font-weight:800;
  font-size:var(--m-t-body);
  color:#fff;
  background: var(--m-ac);
}
.ds6 .m-side__w{min-inline-size:0;overflow:hidden;
           transition:opacity 200ms var(--m-ease) 80ms}
.ds6 .m-side__n{font-size:var(--m-t-sub);font-weight:700;color:var(--m-ink);line-height:1.2}
.ds6 .m-side__r{font-size:var(--m-t-micro);color:var(--m-faint)}
.ds6 .m-side[data-collapsed] .m-side__w{opacity:0;transition:opacity 120ms var(--m-ease)}
.ds6 .m-side__grp{
  font-size:var(--m-t-micro);
  font-weight:700;
  color:var(--m-faint);
  letter-spacing: 0;
  padding:var(--m-4) var(--m-4) var(--m-1);
  white-space:nowrap;
  transition:opacity var(--m-out) var(--m-ease);
}
.ds6 .m-side[data-collapsed] .m-side__grp{opacity:0}
.ds6 .m-side__nav{flex:1 1 auto;min-block-size:0;overflow-y:auto;overflow-x:hidden;
             padding:0 var(--m-2)}
.ds6 .m-nav{
  display:flex;
  align-items:center;
  gap:10px;
  padding:8px var(--m-3);
  min-block-size: 44px;
  border-radius: var(--m-r-ctl);
  color:var(--m-ink-2);
  text-decoration:none;
  font-size: 14px;
  white-space:nowrap;
  position:relative;
  transition:background var(--m-out) var(--m-ease),color var(--m-out) var(--m-ease),
                  transform var(--m-press) var(--m-ease);
  line-height: 24px;
}
.ds6 .m-nav svg{inline-size:20px;block-size:20px;flex:0 0 auto;stroke:currentColor;
           stroke-width:1.7;fill:none;stroke-linecap:round;stroke-linejoin:round}
.ds6 .m-nav span{flex:1 1 auto;min-inline-size:0;overflow:hidden;
            transition:opacity 200ms var(--m-ease) 80ms,transform 200ms var(--m-ease) 80ms}
.ds6 .m-side[data-collapsed] .m-nav span{opacity:0;transform:translateX(4px);
            transition:opacity 120ms var(--m-ease),transform 120ms var(--m-ease)}
.ds6 .m-nav b{font-size:var(--m-t-micro);font-weight:700;background:var(--m-sunk);
         color:var(--m-mut);border-radius:var(--m-r-chip);padding:1px 7px;
         font-variant-numeric:tabular-nums;
         transition:opacity var(--m-out) var(--m-ease)}
.ds6 .m-side[data-collapsed] .m-nav b{opacity:0}
@media (hover:hover) and (pointer:fine){.ds6 .m-nav:hover{background:var(--m-page);color:var(--m-ink)}}
.ds6 .m-nav:active{transform:scale(.98)}
.ds6 .m-nav[aria-current]{background:var(--m-ac-dim);color:var(--m-ac-deep);font-weight:600}
.ds6 .m-nav[aria-current] b{background:var(--m-paper);color:var(--m-ac-deep)}
.ds6 .m-nav:focus-visible{outline:none;box-shadow:var(--m-focus)}
.ds6 .m-nav::after{
  content: none;
  position:absolute;
  inset-inline-end:calc(100% + 10px);
  inset-block-start:50%;
  transform:translateY(-50%) scale(.96);
  transform-origin:center right;
  background:var(--m-ink);
  color:#fff;
  font-size:var(--m-t-cap);
  font-weight:600;
  padding:5px 10px;
  border-radius:var(--m-r-ctl);
  white-space:nowrap;
  pointer-events:none;
  opacity:0;
  z-index:var(--z-sticky, 100);
  transition:opacity var(--m-out) var(--m-ease),
                                  transform var(--m-out) var(--m-ease);
}
@media (hover:hover) and (pointer:fine){.ds6 .m-side[data-collapsed] .m-nav:hover::after{opacity:1;transform:translateY(-50%) scale(1)}}
.ds6 .m-side__f{padding:var(--m-2) var(--m-2) var(--m-3);border-block-start:1px solid var(--m-line)}
.ds6 .m-side__t{display:flex;align-items:center;gap:var(--m-3);inline-size:100%;
           padding:9px var(--m-3);border:0;background:transparent;cursor:pointer;
           border-radius:var(--m-r-ctl);color:var(--m-mut);font:inherit;
           font-size:var(--m-t-cap);white-space:nowrap;
           transition:background var(--m-out) var(--m-ease),transform var(--m-press) var(--m-ease)}
@media (hover:hover) and (pointer:fine){.ds6 .m-side__t:hover{background:var(--m-page)}}
.ds6 .m-side__t:active{transform:scale(.98)}
.ds6 .m-side__t svg{inline-size:18px;block-size:18px;flex:0 0 auto;stroke:currentColor;
               stroke-width:1.7;fill:none;transition:transform var(--m-in) var(--m-ease)}
.ds6 .m-side[data-collapsed] .m-side__t svg{transform:rotate(180deg)}
.ds6 .m-side[data-collapsed] .m-side__t span{opacity:0}
.ds6 .m-main{flex:1 1 auto;min-inline-size:0}
.ds6 .m-bar{
  background: transparent;
  border-block-end: 0;
  padding:var(--m-3) var(--m-6);
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:var(--m-4);
  flex-wrap:wrap;
  position: static;
  inset-block-start:0;
  z-index:var(--z-sticky, 100);
  padding-inline: var(--m-6);
  padding-block: var(--m-3);
}
.ds6 .m-page{
  padding:var(--m-5) var(--m-6) var(--m-7);
  max-inline-size: 1264px;
  inline-size: 100%;
  margin-inline: auto;
  padding-inline: var(--m-6);
  padding-block: var(--m-6) var(--m-7);
}
@media (max-width:900px){.ds6 .m-side{position:fixed;inset-inline-end:0;z-index:var(--z-overlay, 300);transform:translateX(100%);
          transition:transform var(--m-in) var(--m-ease)}.ds6 .m-side[data-open]{transform:none}.ds6 .m-bar, .ds6 .m-page{padding-inline:var(--m-4)}}
.ds6 .m-crumb{font-size:var(--m-t-cap);color:var(--m-faint)}
.ds6 .m-h1{margin:0;font-size:var(--m-t-display);font-weight:800;color:var(--m-ink);
      letter-spacing:-1px;line-height:1.2}
.ds6 .m-head{display:flex;align-items:center;justify-content:space-between;
        gap:var(--m-4);flex-wrap:wrap;margin-block-end:var(--m-5)}
.ds6 .m-head__a{display:flex;gap:var(--m-2);align-items:center;flex-wrap:wrap}
.ds6 .m-search{display:flex;align-items:center;gap:var(--m-2);background:var(--m-page);
          border-radius:var(--m-r-chip);padding:8px var(--m-4);box-shadow:var(--m-hair);
          color:var(--m-faint);font-size:var(--m-t-body);min-inline-size:230px}
.ds6 .m-search svg{inline-size:16px;block-size:16px;stroke:currentColor;stroke-width:1.8;fill:none}
.ds6 .m-kbd{margin-inline-start:auto;display:flex;gap:3px}
.ds6 .m-kbd span{font-size:var(--m-t-micro);font-weight:600;color:var(--m-mut);
            background:var(--m-paper);border-radius:5px;padding:2px 6px;box-shadow:var(--m-hair)}
.ds6 .m-tabs{display:flex;gap:var(--m-1);border-block-end:1px solid var(--m-line);
        overflow-x:auto;position:relative}
.ds6 .m-tab{display:inline-flex;align-items:center;gap:7px;padding:11px var(--m-3);
       color:var(--m-mut);text-decoration:none;font-size:var(--m-t-body);font-weight:500;
       border:0;background:transparent;cursor:pointer;font-family:inherit;
       white-space:nowrap;border-block-end:2px solid transparent;margin-block-end:-1px;
       transition:color var(--m-out) var(--m-ease)}
@media (hover:hover) and (pointer:fine){.ds6 .m-tab:hover{color:var(--m-ink)}}
.ds6 .m-tab[aria-selected="true"]{color:var(--m-ink);font-weight:600;
       border-block-end-color:var(--m-ac)}
.ds6 .m-tab b{font-size:var(--m-t-micro);font-weight:700;background:var(--m-sunk);
         color:var(--m-mut);border-radius:var(--m-r-chip);padding:1px 6px;
         font-variant-numeric:tabular-nums}
.ds6 .m-tab:focus-visible{outline:none;box-shadow:var(--m-focus);border-radius:var(--m-r-sm,6px)}
.ds6 .m-seg{display:inline-flex;background:var(--m-sunk);border-radius:var(--m-r-chip);padding:3px}
.ds6 .m-seg button{font:inherit;font-size:var(--m-t-cap);font-weight:600;border:0;cursor:pointer;
       background:transparent;color:var(--m-mut);padding:5px 13px;border-radius:var(--m-r-chip);
       transition:background var(--m-out) var(--m-ease),color var(--m-out) var(--m-ease),
                  transform var(--m-press) var(--m-ease)}
.ds6 .m-seg button:active{transform:scale(.97)}
.ds6 .m-seg button[aria-pressed="true"]{background:var(--m-paper);color:var(--m-ink);
       box-shadow:var(--m-low)}
.ds6 .m-field{display:flex;flex-direction:column;gap:6px}
.ds6 .m-label{
  font-size:var(--m-t-cap);
  font-weight: 600;
  color:var(--m-ink-2);
}
.ds6 .m-req::after{content:"*";color:var(--m-bad);margin-inline-start:3px}
.ds6 .m-input, .ds6 .m-select{font:inherit;font-size:var(--m-t-body);color:var(--m-ink);
  background:var(--m-paper);border:0;border-radius:10px;
  padding:0 11px;block-size:36px;inline-size:100%;
  box-shadow:0 0 0 1px var(--m-line-2),0 1px 2px rgba(0,0,0,.05),
             inset 0 1px rgba(0,0,0,.04);
  transition:box-shadow 150ms cubic-bezier(.4,0,.2,1)}
.ds6 .m-input::placeholder{color:var(--m-faint);opacity:.72}
.ds6 .m-input:focus, .ds6 .m-select:focus{outline:none;
  box-shadow:0 0 0 1px var(--m-ac),0 0 0 3px var(--m-ac-line)}
.ds6 .m-input[aria-invalid="true"]{box-shadow:0 0 0 1px var(--m-bad),0 0 0 3px var(--m-bad-dim)}
.ds6 textarea.m-input{resize:vertical;line-height:1.7;block-size:auto;padding:9px 11px}
.ds6 .m-select{
  appearance: auto;
  padding-inline-end:32px;
  background-image: none;
  charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%236B7280' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' opacity='.8'%3E%3Cpath d='m6 9 6 6 6-6'/%3E%3C/svg%3E");
  background-repeat:no-repeat;
  background-size:16px;
  background-position:left 10px center;
  padding-inline: var(--m-3);
}
.ds6 .m-hint{font-size:var(--m-t-micro);color:var(--m-faint)}
.ds6 .m-err{font-size:var(--m-t-micro);color:var(--m-bad);font-weight:600}
.ds6 .m-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--m-4)}
.ds6 .m-form .full{grid-column:1 / -1}
@media (max-width:640px){.ds6 .m-form{grid-template-columns:1fr}}
.ds6 .m-chip{display:inline-flex;align-items:center;gap:4px;min-block-size:18px;
        padding:1px 7px;border-radius:6px;font-size:var(--m-t-cap);line-height:16px;
        font-weight:500;white-space:nowrap;
        background:color-mix(in srgb,var(--m-idle) 8%,transparent);color:var(--m-idle)}
.ds6 .m-chip--ok{
  background: var(--m-ok-dim);
  color: var(--m-ok);
}
.ds6 .m-chip--warn{background:color-mix(in srgb,var(--m-warn) 8%,transparent);color:var(--m-warn)}
.ds6 .m-chip--bad{
  background: var(--m-bad-dim);
  color: var(--m-bad);
}
.ds6 .m-chip--ac{
  background: var(--m-ac-dim);
  color: var(--m-ac-deep);
}
.ds6 .m-chip::before{content:"";inline-size:5px;block-size:5px;border-radius:50%;
                background:currentColor;flex:0 0 auto}
.ds6 .m-chip--plain::before{display:none}
.ds6 .m-tip2{position:absolute;padding:4px 8px;border-radius:8px;font-size:var(--m-t-cap);
        line-height:16px;background:var(--m-paper);color:var(--m-ink);
        box-shadow:0 0 0 1px var(--m-line),0 4px 6px -1px rgba(0,0,0,.05),
                   0 2px 4px -2px rgba(0,0,0,.05),inset 0 1px rgba(0,0,0,.04);
        opacity:0;transform:scale(.98);pointer-events:none;
        transition:opacity 150ms cubic-bezier(.4,0,.2,1),
                   transform 150ms cubic-bezier(.4,0,.2,1)}
.ds6 .m-tip2[data-open]{opacity:1;transform:none}
.ds6 .m-tablewrap{
  position:relative;
  inline-size:100%;
  overflow-x:auto;
  border-radius: 0 0 var(--m-r-card) var(--m-r-card);
  overflow: auto;
}
.ds6 .m-table{inline-size:100%;border-collapse:collapse}
.ds6 .m-table th{
  block-size: 44px;
  padding:0 10px;
  font-size: 13px;
  font-weight: 500;
  line-height: 22px;
  color: var(--m-mut);
  text-align: start;
  white-space:nowrap;
  background: var(--m-paper);
  border-block-end:1px solid var(--m-line);
  padding-inline: var(--m-4);
  padding-block: var(--m-2);
}
.ds6 .m-table td{
  padding:10px;
  font-size: 15px;
  font-weight: 400;
  line-height: 24px;
  color: var(--m-ink-2);
  vertical-align:middle;
  border-block-start:1px solid var(--m-line);
  padding-inline: var(--m-4);
  padding-block: 10px;
}
.ds6 .m-table tbody tr{transition:background-color 150ms cubic-bezier(.4,0,.2,1)}
@media (hover:hover) and (pointer:fine){.ds6 .m-table tbody tr:hover{background:var(--m-page)}}
.ds6 .m-table tbody tr[aria-selected="true"]{background:var(--m-sunk)}
.ds6 .m-table--sticky thead th{position:sticky;inset-block-start:0;z-index:var(--z-sticky, 100);
            background:var(--m-paper)}
.ds6 .m-th-sort{display:flex;align-items:center;gap:4px;inline-size:100%;block-size:100%;
           font:inherit;color:inherit;background:none;border:0;cursor:pointer;
           padding:0;text-align:start}
.ds6 .m-th-sort svg{inline-size:14px;block-size:14px;flex:0 0 auto;opacity:.35;
           stroke:currentColor;stroke-width:2;fill:none;
           transition:transform 180ms cubic-bezier(.16,1,.3,1),
                      opacity 180ms cubic-bezier(.16,1,.3,1)}
.ds6 .m-table th[aria-sort] .m-th-sort svg{opacity:1}
.ds6 .m-table th[aria-sort="descending"] .m-th-sort svg{transform:rotate(180deg)}
.ds6 .m-table th.m-sel{inline-size:26px;padding:0 0 0 10px}
.ds6 .m-table td.m-sel{padding:10px 0 10px 9px}
.ds6 .m-table tfoot td{block-size:43px;padding:14px 10px;font-weight:600;color:var(--m-ink);
            background:var(--m-page);border-block-start:1px solid var(--m-line-2)}
.ds6 .m-td-n{font-weight:600;color:var(--m-ink)}
.ds6 .m-td-v{text-align:end;font-variant-numeric:tabular-nums;font-feature-settings:"tnum" 1;
        font-weight:600;color:var(--m-ink);white-space:nowrap}
.ds6 .m-table th.num{text-align:end}
.ds6 .m-td-nil{color:var(--m-faint);font-weight:400}
.ds6 .m-table__empty td{padding:0}
.ds6 .m-tools{display:flex;align-items:center;justify-content:space-between;gap:var(--m-3);
         padding:var(--m-3);flex-wrap:wrap}
.ds6 .m-cb{inline-size:16px;block-size:16px;border-radius:4px;appearance:none;cursor:pointer;
      background:var(--m-paper);box-shadow:0 0 0 1px var(--m-line-2),0 1px 2px rgba(0,0,0,.05);
      display:grid;place-items:center;transition:box-shadow 150ms cubic-bezier(.4,0,.2,1)}
.ds6 .m-cb:checked{background:var(--m-ac);box-shadow:0 0 0 1px var(--m-ac)}
.ds6 .m-cb:checked::after{content:"";inline-size:9px;block-size:5px;border:2px solid #fff;
      border-block-start:0;border-inline-end:0;transform:rotate(-45deg) translate(1px,-1px)}
.ds6 .m-cb:focus-visible{outline:none;box-shadow:0 0 0 1px var(--m-ac),var(--m-focus)}
.ds6 .m-av{inline-size:30px;block-size:30px;border-radius:50%;flex:0 0 auto;display:grid;
      place-items:center;font-size:var(--m-t-cap);font-weight:700;
      background:var(--m-ac-dim);color:var(--m-ac-deep)}
.ds6 .m-av--sq{border-radius:9px;background:var(--m-sunk);color:var(--m-ink-2)}
.ds6 .m-crumb{font-size:var(--m-t-cap);color:var(--m-faint);margin-block-end:var(--m-3)}
.ds6 .m-greet{display:flex;align-items:flex-end;justify-content:space-between;
         gap:var(--m-5);flex-wrap:wrap;margin-block-end:var(--m-5)}
.ds6 .m-greet__t{margin:0;font-size:var(--m-t-display);font-weight:800;color:var(--m-ink);
            letter-spacing:-1px;line-height:1.2}
.ds6 .m-greet__s{font-size:var(--m-t-sub);color:var(--m-mut);margin-block-start:var(--m-2)}
.ds6 .m-greet__a{display:flex;gap:var(--m-2);align-items:center;flex-wrap:wrap}
.ds6 .m-search{display:flex;align-items:center;gap:var(--m-2);background:var(--m-paper);
          border-radius:var(--m-r-chip);padding:9px var(--m-4);box-shadow:var(--m-low);
          color:var(--m-faint);font-size:var(--m-t-body);min-inline-size:240px}
.ds6 .m-kbd{margin-inline-start:auto;display:flex;gap:3px}
.ds6 .m-kbd span{font-size:var(--m-t-micro);font-weight:600;color:var(--m-mut);
            background:var(--m-page);border-radius:5px;padding:2px 6px;box-shadow:var(--m-hair)}
.ds6 .m-card{
  background: var(--m-paper);
  border-radius: var(--m-r-card);
  box-shadow: none;
  padding:var(--m-5);
  min-inline-size: 0;
  padding-inline: var(--m-5);
  padding-block: var(--m-5);
  border: 1px solid var(--m-line);
}
.ds6 .m-card--band{border-radius:var(--m-r-band);padding:var(--m-6)}
.ds6 .m-card--pad0{padding:0}
.ds6 .m-card__h{display:flex;align-items:flex-start;justify-content:space-between;
           gap:var(--m-3);margin-block-end:var(--m-4)}
.ds6 .m-card__t{margin:0;font-size:var(--m-t-h);font-weight:700;color:var(--m-ink);
           letter-spacing:-.3px}
.ds6 .m-card__k{font-size:var(--m-t-body);color:var(--m-mut);font-weight:500}
.ds6 .m-lead{display:flex;align-items:center;gap:var(--m-4);flex-wrap:wrap}
.ds6 .m-lead__v{font-size:var(--m-t-hero);font-weight:800;color:var(--m-ink);
           letter-spacing:-2.5px;line-height:1.05;font-variant-numeric:tabular-nums}
.ds6 .m-lead__v small{font-size:var(--m-t-h);font-weight:600;color:var(--m-mut);
                 letter-spacing:0;margin-inline-start:var(--m-2)}
.ds6 .m-delta{display:inline-flex;align-items:center;gap:6px;font-size:var(--m-t-body);
         font-weight:600;padding:6px 13px;border-radius:var(--m-r-chip);
         background:var(--m-ok-dim);color:var(--m-ok)}
.ds6 .m-delta--bad{background:var(--m-bad-dim);color:var(--m-bad)}
.ds6 .m-delta--warn{background:var(--m-warn-dim);color:var(--m-warn)}
.ds6 .m-delta--flat{background:var(--m-idle-dim);color:var(--m-idle)}
.ds6 .m-stat__k{font-size:var(--m-t-cap);color:var(--m-mut);font-weight:500}
.ds6 .m-stat__v{font-size:var(--m-t-fig);font-weight:800;color:var(--m-ink);line-height:1.2;
           margin-block-start:var(--m-1);letter-spacing:-.8px;
           font-variant-numeric:tabular-nums}
.ds6 .m-stat__v small{font-size:var(--m-t-cap);font-weight:600;color:var(--m-mut);
                 letter-spacing:0;margin-inline-start:4px}
.ds6 .m-stat__s{font-size:var(--m-t-micro);color:var(--m-faint);margin-block-start:3px}
.ds6 .m-stat--ac .m-stat__v{color:var(--m-ac)}
.ds6 .m-stat--mut .m-stat__v{color:var(--m-faint)}
.ds6 .m-stats{display:flex;gap:var(--m-6);flex-wrap:wrap}
.ds6 .m-chart{display:block;inline-size:100%;block-size:auto;overflow:visible}
.ds6 .m-chart__ax{font-size:var(--m-t-cap);fill:var(--m-mut);font-family:inherit}
.ds6 .m-chart__bar{fill:url(#mBar)}
.ds6 .m-chart__cap{fill:var(--m-ac)}
.ds6 .m-chart__cap--vi{fill:var(--m-vi)}
.ds6 .m-chart__trend{stroke:var(--m-ac-line);stroke-width:2;stroke-dasharray:5 5;fill:none}
.ds6 .m-chart__zero{stroke:var(--m-line-2);stroke-width:1}
.ds6 .m-chart__now{stroke:var(--m-line-2);stroke-width:1;stroke-dasharray:3 4}
.ds6 .m-chart__grow{transform-box:fill-box;transform-origin:bottom;
               animation:m-grow 700ms var(--m-ease) both}
@keyframes m-grow{from{transform:scaleY(.02);opacity:0}to{transform:scaleY(1);opacity:1}}
@media (prefers-reduced-motion:reduce){.ds6 .m-chart__grow{animation:none}}
.ds6 .m-tip{position:absolute;background:var(--m-paper);border-radius:var(--m-r-ctl);
       box-shadow:var(--m-lift);padding:var(--m-3) var(--m-4);pointer-events:none}
.ds6 .m-tip__d{font-size:var(--m-t-cap);color:var(--m-mut);margin-block-end:var(--m-2)}
.ds6 .m-tip__g{display:flex;gap:var(--m-5)}
.ds6 .m-tip__k{font-size:var(--m-t-cap);color:var(--m-mut)}
.ds6 .m-tip__v{font-size:var(--m-t-sub);font-weight:700;color:var(--m-ink);
          font-variant-numeric:tabular-nums}
.ds6 .m-tip__v--bad{color:var(--m-bad)}
.ds6 .m-seg-bar{display:flex;align-items:center;gap:3px;margin-block:var(--m-3) var(--m-2)}
.ds6 .m-seg-bar i{block-size:8px;flex:1 1 auto;border-radius:99px;background:var(--m-sunk)}
.ds6 .m-seg-bar i.on{background:var(--m-ac)}
.ds6 .m-seg-bar b{inline-size:16px;block-size:16px;border-radius:50%;background:var(--m-paper);
             box-shadow:0 0 0 3px var(--m-ac),0 1px 3px rgba(16,24,40,.2);flex:0 0 auto}
.ds6 .m-board{display:flex;gap:var(--m-3);align-items:flex-start;overflow-x:auto;
         padding-block-end:var(--m-2)}
.ds6 .m-col{inline-size:252px;flex:0 0 auto;display:flex;flex-direction:column;
       background:var(--m-page);border-radius:var(--m-r-ctl);padding:var(--m-3)}
.ds6 .m-col__t{display:flex;align-items:center;gap:var(--m-2);margin-block-end:var(--m-1)}
.ds6 .m-col__dot{inline-size:8px;block-size:8px;border-radius:50%;flex:0 0 auto;
            background:var(--m-tone,var(--m-idle))}
.ds6 .m-col__n{font-size:var(--m-t-body);font-weight:600;color:var(--m-ink);flex:1 1 auto}
.ds6 .m-col__c{font-size:var(--m-t-micro);font-weight:700;color:var(--m-mut);
          background:var(--m-paper);border-radius:var(--m-r-chip);padding:1px 7px;
          box-shadow:var(--m-hair);font-variant-numeric:tabular-nums}
.ds6 .m-col__v{font-size:var(--m-t-cap);color:var(--m-mut);padding-inline-start:16px;
          margin-block-end:var(--m-2);font-variant-numeric:tabular-nums}
.ds6 .m-col__b{display:flex;flex-direction:column;gap:var(--m-2)}
.ds6 .m-col--rail{inline-size:44px;cursor:pointer;align-self:stretch}
.ds6 .m-col--rail .m-col__b, .ds6 .m-col--rail .m-col__v{display:none}
.ds6 .m-col--rail .m-col__t{flex-direction:column;gap:var(--m-3);margin:0}
.ds6 .m-col--rail .m-col__n{writing-mode:vertical-rl;transform:rotate(180deg);
            white-space:nowrap;flex:0 0 auto;font-size:var(--m-t-cap);color:var(--m-mut)}
@media (hover:hover) and (pointer:fine){.ds6 .m-col--rail:hover{background:var(--m-sunk)}}
.ds6 .m-deal{background:var(--m-paper);border-radius:var(--m-r-ctl);padding:var(--m-3);
        box-shadow:var(--m-low);cursor:grab;
        transition:box-shadow var(--m-out) var(--m-ease),transform var(--m-press) var(--m-ease)}
@media (hover:hover) and (pointer:fine){.ds6 .m-deal:hover{box-shadow:var(--m-lift)}}
.ds6 .m-deal:active{cursor:grabbing;transform:scale(.985)}
.ds6 .m-deal:focus-visible{outline:none;box-shadow:var(--m-focus),var(--m-low)}
.ds6 .m-deal__n{font-size:var(--m-t-body);font-weight:700;color:var(--m-ink);
           display:flex;align-items:center;justify-content:space-between;gap:var(--m-2)}
.ds6 .m-deal__p{font-size:var(--m-t-cap);color:var(--m-mut);margin-block-start:2px}
.ds6 .m-deal__f{display:flex;align-items:center;justify-content:space-between;
           gap:var(--m-2);margin-block-start:var(--m-2)}
.ds6 .m-deal__v{font-size:var(--m-t-sub);font-weight:700;color:var(--m-ink);
           font-variant-numeric:tabular-nums}
.ds6 .m-deal__v--nil{font-size:var(--m-t-cap);font-weight:600;color:var(--m-warn)}
.ds6 .m-deal__age{font-size:var(--m-t-micro);color:var(--m-faint);font-variant-numeric:tabular-nums}
.ds6 .m-deal__age--old{color:var(--m-warn);font-weight:600}
.ds6 .m-empty-col{padding:var(--m-4) var(--m-3);text-align:center;border-radius:var(--m-r-ctl);
             border:1px dashed var(--m-line-2);color:var(--m-faint);
             font-size:var(--m-t-cap);line-height:1.7}
.ds6 .m-item{display:flex;align-items:center;gap:var(--m-3);padding:var(--m-3) 0;
        border-block-start:1px solid var(--m-line)}
.ds6 .m-item:first-child{border-block-start:0}
.ds6 .m-item__m{inline-size:38px;block-size:38px;border-radius:50%;flex:0 0 auto;
           display:grid;place-items:center;font-size:var(--m-t-body);font-weight:700;
           background:var(--m-page);color:var(--m-ink-2);box-shadow:var(--m-hair)}
.ds6 .m-item__b{flex:1 1 auto;min-inline-size:0}
.ds6 .m-item__n{font-size:var(--m-t-body);font-weight:600;color:var(--m-ink)}
.ds6 .m-item__s{font-size:var(--m-t-cap);color:var(--m-faint);margin-block-start:1px}
.ds6 .m-item__v{font-size:var(--m-t-body);font-weight:700;color:var(--m-ink);
           font-variant-numeric:tabular-nums;white-space:nowrap}
.ds6 .m-insight{border-radius:var(--m-r-band);padding:var(--m-5);color:#fff;
  background:
    radial-gradient(circle at 1px 1px,rgba(255,255,255,.32) 1px,transparent 0) 0 0/8px 8px,
    linear-gradient(150deg,#1D4FD8,#2F6BFF 45%,#8B5CF6);
  display:flex;flex-direction:column;gap:var(--m-3)}
.ds6 .m-insight__k{font-size:var(--m-t-cap);opacity:.85;font-weight:600}
.ds6 .m-insight__t{font-size:var(--m-t-h);font-weight:700;letter-spacing:-.3px;line-height:1.35}
.ds6 .m-insight__c{background:var(--m-paper);border-radius:var(--m-r-ctl);padding:var(--m-3) var(--m-4);
              color:var(--m-ink-2);font-size:var(--m-t-cap);line-height:1.75}
.ds6 .m-insight__c b{color:var(--m-ink)}
.ds6 .m-dots{display:flex;gap:5px}
.ds6 .m-dots i{inline-size:16px;block-size:4px;border-radius:99px;background:rgba(255,255,255,.35)}
.ds6 .m-dots i.on{background:#fff;inline-size:22px}
.ds6 .m-chip{display:inline-flex;align-items:center;gap:6px;font-size:var(--m-t-micro);
        font-weight:600;padding:3px 9px;border-radius:var(--m-r-chip);
        background:var(--m-idle-dim);color:var(--m-idle);white-space:nowrap}
.ds6 .m-chip--ok{
  background: var(--m-ok-dim);
  color: var(--m-ok);
}
.ds6 .m-chip--warn{background:var(--m-warn-dim);color:var(--m-warn)}
.ds6 .m-chip--bad{
  background: var(--m-bad-dim);
  color: var(--m-bad);
}
.ds6 .m-chip--ac{
  background: var(--m-ac-dim);
  color: var(--m-ac-deep);
}
.ds6 .m-chip::before{content:"";inline-size:5px;block-size:5px;border-radius:50%;background:currentColor}
.ds6 .m-chip--plain::before{display:none}
.ds6 .m-btn{
  display:inline-flex;
  align-items:center;
  gap:7px;
  font:inherit;
  font-size: 14px;
  font-weight:600;
  padding:9px 16px;
  border-radius: var(--m-r-chip);
  border: 1px solid var(--m-line-2);
  cursor:pointer;
  background:var(--m-paper);
  color:var(--m-ink);
  box-shadow: none;
  transition:
    background-color var(--m-out) var(--m-ease),
    transform var(--m-press) var(--m-ease);
  min-block-size: 44px;
  justify-content: center;
  padding-inline: var(--m-4);
  padding-block: 9px;
  line-height: 24px;
  text-decoration: none;
}
.ds6 .m-btn:active{transform:scale(.97)}
@media (hover:hover) and (pointer:fine){.ds6 .m-btn:hover{background:var(--m-page)}}
.ds6 .m-btn--primary{
  background: var(--m-ac);
  color: #FFFFFF;
  box-shadow: none;
  border-color: var(--m-ac);
}
@media (hover:hover) and (pointer:fine){.ds6 .m-btn--primary:hover{background:var(--m-ac-deep)}}
.ds6 .m-btn--primary:active{background:var(--m-ac-deep)}
.ds6 .m-btn--icon{
  padding:9px;
  inline-size: 44px;
  block-size: 44px;
  justify-content:center;
}
.ds6 .m-btn--quiet{
  background: transparent;
  box-shadow:none;
  color: var(--m-ac-deep);
  padding-inline:6px;
  border-color: transparent;
}
.ds6 .m-btn[disabled]{color:var(--m-faint);cursor:not-allowed;background:var(--m-sunk);box-shadow:none}
.ds6 .m-btn:focus-visible{outline:none;box-shadow:var(--m-focus),var(--m-low)}
.ds6 .m-link{
  font-size: 14px;
  font-weight:600;
  color: var(--m-ac-deep);
  text-decoration: underline;
  display: inline-flex;
  align-items: center;
  min-block-size: 44px;
  line-height: 24px;
  text-underline-offset: 4px;
}
@media (hover:hover) and (pointer:fine){.ds6 .m-link:hover{text-decoration:underline}}
.ds6 .m-alert{display:flex;align-items:center;gap:var(--m-3);flex-wrap:wrap;
         background:var(--m-warn-dim);border-radius:var(--m-r-card);
         padding:var(--m-3) var(--m-4);box-shadow:0 0 0 1px var(--m-warn-line)}
.ds6 .m-alert__t{font-size:var(--m-t-body);font-weight:700;color:var(--m-warn)}
.ds6 .m-alert__d{font-size:var(--m-t-cap);color:var(--m-ink-2);flex:1 1 240px}
.ds6 .m-empty{
  padding:var(--m-6) var(--m-5);
  text-align: start;
  padding-inline: var(--m-5);
  padding-block: var(--m-5);
}
.ds6 .m-empty__t{
  font-size: 15px;
  font-weight:700;
  color:var(--m-ink);
  line-height: 26px;
}
.ds6 .m-empty__d{
  font-size: 13px;
  color:var(--m-mut);
  margin-block-start:var(--m-2);
  max-inline-size: 60ch;
  margin-inline: 0;
  line-height: 22px;
}
.ds6 .m-empty__a{margin-block-start:var(--m-4)}
.ds6 .m-nil{color:var(--m-faint);font-size:var(--m-t-cap)}
.ds6 .m-grid{display:grid;gap:var(--m-4)}
.ds6 .m-grid--main{grid-template-columns:minmax(0,1fr) 340px}
.ds6 .m-grid--3{grid-template-columns:repeat(3,minmax(0,1fr))}
@media (max-width:1180px){.ds6 .m-grid--main{grid-template-columns:1fr}}
@media (max-width:980px){.ds6 .m-grid--3{grid-template-columns:1fr}}
.ds6 .m-between{display:flex;align-items:center;justify-content:space-between;gap:var(--m-3)}
.ds6 .m-row{display:flex;align-items:center;gap:var(--m-2)}
.ds6 .m-cap{font-size:var(--m-t-cap);color:var(--m-mut)}
.ds6 .m-rel{position:relative}
.ds6 .m-arc{position:relative;inline-size:100%;max-inline-size:200px;margin-inline:auto}
.ds6 .m-arc svg{display:block;inline-size:100%;block-size:auto;overflow:visible}
.ds6 .m-arc__track{fill:none;stroke:var(--m-sunk);stroke-width:14;stroke-linecap:round}
.ds6 .m-arc__fill{fill:none;stroke:var(--m-ac);stroke-width:14;stroke-linecap:round;
             stroke-dasharray:var(--m-dash,0) 999;
             animation:m-arc 900ms var(--m-ease) both}
.ds6 .m-arc__fill--warn{stroke:var(--m-warn)}
.ds6 .m-arc__fill--bad{stroke:var(--m-bad)}
.ds6 .m-arc__fill--ok{stroke:var(--m-ok)}
@keyframes m-arc{from{stroke-dasharray:0 999}}
@media (prefers-reduced-motion:reduce){.ds6 .m-arc__fill{animation:none}}
.ds6 .m-arc__c{position:absolute;inset-inline:0;inset-block-end:6%;text-align:center}
.ds6 .m-arc__v{font-size:var(--m-t-display);font-weight:800;color:var(--m-ink);
          letter-spacing:-1.5px;line-height:1;font-variant-numeric:tabular-nums}
.ds6 .m-arc__k{font-size:var(--m-t-cap);color:var(--m-mut);margin-block-start:var(--m-1)}
.ds6 .m-matrix{display:flex;flex-wrap:wrap;gap:5px;margin-block:var(--m-3)}
.ds6 .m-matrix i{inline-size:12px;block-size:12px;border-radius:4px;background:var(--m-sunk)}
.ds6 .m-matrix i.is-ok{background:var(--m-ok-line)}
.ds6 .m-matrix i.is-ac{background:var(--m-ac)}
.ds6 .m-matrix i.is-warn{background:var(--m-warn-line)}
.ds6 .m-matrix i.is-bad{background:var(--m-bad-line)}
.ds6 .m-matrix i.is-idle{background:var(--m-line-2)}
.ds6 .m-key{display:flex;gap:var(--m-4);flex-wrap:wrap;font-size:var(--m-t-cap);color:var(--m-mut)}
.ds6 .m-key span{display:inline-flex;align-items:center;gap:6px}
.ds6 .m-key i{inline-size:10px;block-size:10px;border-radius:3px}
.ds6 .m-funnel{display:flex;flex-direction:column;gap:var(--m-2)}
.ds6 .m-fstep{display:grid;grid-template-columns:104px 1fr auto;align-items:center;gap:var(--m-3)}
.ds6 .m-fstep__k{font-size:var(--m-t-cap);color:var(--m-mut)}
.ds6 .m-fstep__b{block-size:30px;border-radius:var(--m-r-ctl);background:var(--m-sunk);
            position:relative;overflow:hidden}
.ds6 .m-fstep__b i{position:absolute;inset-block:0;inset-inline-start:0;inline-size:var(--m-pct,0%);
              background:linear-gradient(90deg,var(--m-ac),var(--m-vi));border-radius:var(--m-r-ctl);
              animation:m-fgrow 700ms var(--m-ease) both}
@keyframes m-fgrow{from{inline-size:0}}
@media (prefers-reduced-motion:reduce){.ds6 .m-fstep__b i{animation:none}}
.ds6 .m-fstep__v{font-size:var(--m-t-body);font-weight:700;color:var(--m-ink);
            font-variant-numeric:tabular-nums;min-inline-size:56px;text-align:start}
.ds6 .m-fstep__d{font-size:var(--m-t-micro);color:var(--m-bad);font-weight:600}
.ds6 .m-heat{display:flex;gap:4px;margin-block:var(--m-3)}
.ds6 .m-heat i{flex:1 1 auto;block-size:34px;border-radius:5px;background:var(--m-sunk)}
.ds6 .m-heat i.l1{background:var(--m-ac-line)}
.ds6 .m-heat i.l2{background:#9CC0FF}
.ds6 .m-heat i.l3{background:var(--m-ac)}
.ds6 .m-heat__ax{display:flex;justify-content:space-between;font-size:var(--m-t-micro);
            color:var(--m-faint)}
.ds6 .m-meter{block-size:10px;border-radius:99px;background:var(--m-sunk);position:relative;
         margin-block:var(--m-3) var(--m-2)}
.ds6 .m-meter i{position:absolute;inset-block:0;inset-inline-start:0;inline-size:var(--m-pct,0%);
           border-radius:99px;background:linear-gradient(90deg,var(--m-ac),var(--m-vi))}
.ds6 .m-meter b{position:absolute;inset-block:-4px;inset-inline-start:var(--m-mark,50%);
           inline-size:2px;background:var(--m-ink);opacity:.35}
.ds6 .m-segs{display:flex;flex-direction:column;gap:var(--m-2)}
.ds6 .m-seg-row{display:grid;grid-template-columns:1fr 92px 44px;align-items:center;gap:var(--m-3);
           font-size:var(--m-t-cap)}
.ds6 .m-seg-row__t{color:var(--m-ink-2)}
.ds6 .m-seg-row__b{block-size:6px;border-radius:99px;background:var(--m-sunk);overflow:hidden}
.ds6 .m-seg-row__b i{display:block;block-size:100%;inline-size:var(--m-pct,0%);border-radius:99px;
                background:var(--m-ac)}
.ds6 .m-seg-row__b i.low{background:var(--m-bad)}
.ds6 .m-seg-row__b i.mid{background:var(--m-warn)}
.ds6 .m-seg-row__v{font-weight:700;color:var(--m-ink);font-variant-numeric:tabular-nums;text-align:start}
.ds6 .m-view{position:relative}
.ds6 .m-view__p{transition:opacity var(--m-swap) var(--m-ease),
                      transform var(--m-swap) var(--m-ease),
                      filter var(--m-swap) var(--m-ease)}
.ds6 .m-view__p[hidden]{display:none!important}
.ds6 .m-view__p[data-enter]{opacity:0;transform:translateY(6px);filter:blur(3px)}
@media (prefers-reduced-motion:reduce){.ds6 .m-view__p[data-enter]{transform:none;filter:none}}
.ds6 .m-dates{display:flex;align-items:center;gap:var(--m-2);flex-wrap:wrap}
.ds6 .m-range{display:flex;align-items:center;gap:var(--m-2);background:var(--m-paper);
         border-radius:var(--m-r-chip);padding:5px 6px 5px var(--m-3);box-shadow:var(--m-hair)}
.ds6 .m-range input{font:inherit;font-size:var(--m-t-cap);color:var(--m-ink);border:0;
               background:transparent;padding:3px;inline-size:126px;
               font-variant-numeric:tabular-nums}
.ds6 .m-range input:focus{outline:none;box-shadow:var(--m-focus);border-radius:6px}
.ds6 .m-range span{color:var(--m-faint);font-size:var(--m-t-cap)}
.ds6 .m-qs{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:var(--m-line);
      border-radius:var(--m-r-card);overflow:hidden;box-shadow:var(--m-hair)}
.ds6 .m-q{background:var(--m-paper);padding:var(--m-3) var(--m-4);cursor:pointer;
     transition:background var(--m-out) var(--m-ease)}
@media (hover:hover) and (pointer:fine){.ds6 .m-q:hover{background:var(--m-page)}}
.ds6 .m-q__k{font-size:var(--m-t-cap);color:var(--m-mut);display:flex;align-items:center;gap:6px}
.ds6 .m-q__k i{inline-size:6px;block-size:6px;border-radius:50%;background:var(--m-ac)}
.ds6 .m-q__v{font-size:var(--m-t-fig);font-weight:800;color:var(--m-ink);letter-spacing:-.8px;
        margin-block-start:2px;font-variant-numeric:tabular-nums}
.ds6 .m-q__v.nil{color:var(--m-faint)}
.ds6 .m-q__s{font-size:var(--m-t-micro);color:var(--m-faint);margin-block-start:2px}
.ds6 .m-q__b{block-size:4px;border-radius:99px;background:var(--m-sunk);margin-block-start:var(--m-2);
        overflow:hidden}
.ds6 .m-q__b i{display:block;block-size:100%;inline-size:var(--m-pct,0%);border-radius:99px;
          background:var(--m-ac);transition:inline-size var(--m-in) var(--m-move)}
.ds6 .m-q[aria-current]{background:var(--m-ac-dim)}
.ds6 .m-q[aria-current] .m-q__k{color:var(--m-ac-deep);font-weight:600}
.ds6 .m-mini{inline-size:100%;border-collapse:collapse}
.ds6 .m-mini th{font-size:var(--m-t-micro);font-weight:600;color:var(--m-mut);text-align:start;
           padding:var(--m-2) var(--m-3);border-block-end:1px solid var(--m-line)}
.ds6 .m-mini td{padding:9px var(--m-3);border-block-start:1px solid var(--m-line);
           font-size:var(--m-t-body);font-variant-numeric:tabular-nums}
.ds6 .m-mini td:first-child{color:var(--m-ink);font-weight:600;font-variant-numeric:normal}
.ds6 .m-mini tr[data-now]{background:var(--m-ac-dim)}
.ds6 .m-mini .gap{color:var(--m-bad);font-weight:600}
.ds6 a.m-item{text-decoration:none;color:inherit;
         transition:background var(--m-out) var(--m-ease)}
@media (hover:hover) and (pointer:fine){.ds6 a.m-item:hover{background:var(--m-page)}}
.ds6 a.m-item:focus-visible{outline:none;box-shadow:var(--m-focus);border-radius:var(--m-r-ctl)}
.ds6 .m-item__b{display:block}
.ds6 .m-item__n, .ds6 .m-item__s{display:block}
.ds6 .m-board{align-items:flex-start}
.ds6 .m-col{align-self:flex-start}
.ds6 .m-col--rail{align-self:stretch;min-block-size:150px}
.ds6 .m-side__n, .ds6 .m-side__r{display:block}
.ds6 .m-crumb a{color:inherit;text-decoration:none}
@media (hover:hover) and (pointer:fine){.ds6 .m-crumb a:hover{color:var(--m-ac-deep)}}
.ds6 dialog.m-dlg{border:0;padding:0;background:transparent;max-inline-size:min(680px,92vw);
             inline-size:100%}
.ds6 dialog.m-dlg::backdrop{
  background:rgba(11,13,18,.44);
  backdrop-filter:blur(2px);
  animation: m-fade var(--m-in) var(--m-ease);
}
@keyframes m-fade{from{opacity:0}}
.ds6 .m-dlg__p{
  background:var(--m-paper);
  border-radius:var(--m-r-band);
  box-shadow:var(--m-lift);
  animation: m-dialog-enter var(--m-in) var(--m-ease);
}
@keyframes m-pop{from{opacity:0;transform:scale(.97) translateY(8px)}}
@media (prefers-reduced-motion:reduce){.ds6 .m-dlg__p, .ds6 dialog.m-dlg::backdrop{animation:none}}
.ds6 .m-dlg__h{display:flex;align-items:center;justify-content:space-between;gap:var(--m-3);
          padding:var(--m-4) var(--m-5);border-block-end:1px solid var(--m-line)}
.ds6 .m-dlg__t{margin:0;font-size:var(--m-t-h);font-weight:700;color:var(--m-ink)}
.ds6 .m-dlg__b{padding:var(--m-5);max-block-size:66vh;overflow-y:auto}
.ds6 .m-dlg__f{display:flex;justify-content:flex-end;gap:var(--m-2);
          padding:var(--m-3) var(--m-5);border-block-start:1px solid var(--m-line)}
.ds6 .m-x{inline-size:32px;block-size:32px;border-radius:50%;border:0;cursor:pointer;
     background:transparent;color:var(--m-mut);font-size:18px;line-height:1;
     transition:background var(--m-out) var(--m-ease)}
@media (hover:hover) and (pointer:fine){.ds6 .m-x:hover{background:var(--m-page)}}
.ds6 .m-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--m-4)}
.ds6 .m-form .full{grid-column:1 / -1}
@media (max-width:640px){.ds6 .m-form{grid-template-columns:1fr}}
.ds6 textarea.m-input{resize:vertical;line-height:1.7}
.ds6 .m-req::after{content:"*";color:var(--m-bad);margin-inline-start:3px}
.ds6 .m-kb{display:grid;grid-template-columns:260px minmax(0,1fr);gap:var(--m-4)}
@media (max-width:900px){.ds6 .m-kb{grid-template-columns:1fr}}
.ds6 .m-kb__l{display:flex;flex-direction:column;gap:2px}
.ds6 .m-kb__i{display:flex;align-items:center;justify-content:space-between;gap:var(--m-2);
         padding:9px var(--m-3);border-radius:var(--m-r-ctl);border:0;background:transparent;
         cursor:pointer;font:inherit;font-size:var(--m-t-body);color:var(--m-ink-2);
         text-align:start;transition:background var(--m-out) var(--m-ease)}
@media (hover:hover) and (pointer:fine){.ds6 .m-kb__i:hover{background:var(--m-page)}}
.ds6 .m-kb__i[aria-current]{background:var(--m-ac-dim);color:var(--m-ac-deep);font-weight:600}
.ds6 .m-kb__i b{font-size:var(--m-t-micro);font-weight:700;font-variant-numeric:tabular-nums}
.ds6 .m-kb__i b.low{color:var(--m-bad)}
.ds6 .m-kb__i b.mid{color:var(--m-warn)}
.ds6 .m-kb__i b.ok{color:var(--m-ok)}
.ds6 .m-steps{display:flex;gap:var(--m-2);margin-block-end:var(--m-5);flex-wrap:wrap}
.ds6 .m-step{display:flex;align-items:center;gap:var(--m-2);font-size:var(--m-t-cap);
        color:var(--m-faint)}
.ds6 .m-step i{inline-size:22px;block-size:22px;border-radius:50%;display:grid;place-items:center;
          font-size:var(--m-t-micro);font-weight:700;background:var(--m-sunk);color:var(--m-mut);
          font-variant-numeric:tabular-nums}
.ds6 .m-step[aria-current]{color:var(--m-ink);font-weight:600}
.ds6 .m-step[aria-current] i{background:var(--m-ac);color:#fff}
.ds6 .m-step[data-done] i{background:var(--m-ok-dim);color:var(--m-ok)}
.ds6 .m-step::after{content:"";inline-size:22px;block-size:1px;background:var(--m-line-2)}
.ds6 .m-step:last-child::after{display:none}
.ds6 .m-tl{display:flex;flex-direction:column}
.ds6 .m-tl__i{display:grid;grid-template-columns:22px minmax(0,1fr) auto;gap:var(--m-3);
         padding:var(--m-3) 0;position:relative}
.ds6 .m-tl__d{inline-size:9px;block-size:9px;border-radius:50%;background:var(--m-ac);
         margin-block-start:6px;margin-inline-start:6px;position:relative;z-index:var(--z-base, 0)}
.ds6 .m-tl__d.ok{background:var(--m-ok)}
.ds6 .m-tl__d.warn{background:var(--m-warn)}
.ds6 .m-tl__d.idle{background:var(--m-line-2)}
.ds6 .m-tl__i:not(:last-child)::before{content:"";position:absolute;inset-block:22px -6px;
         inset-inline-start:10px;inline-size:1px;background:var(--m-line)}
.ds6 .m-tl__n{font-size:var(--m-t-body);color:var(--m-ink)}
.ds6 .m-tl__s{font-size:var(--m-t-cap);color:var(--m-faint);margin-block-start:2px}
.ds6 .m-tl__t{font-size:var(--m-t-micro);color:var(--m-faint);white-space:nowrap;
         font-variant-numeric:tabular-nums}
.ds6 .m-sw{inline-size:38px;block-size:22px;border-radius:99px;background:var(--m-line-2);
      border:0;cursor:pointer;padding:0;position:relative;flex:0 0 auto;
      transition:background var(--m-out) var(--m-ease)}
.ds6 .m-sw::after{content:"";position:absolute;inset-block-start:3px;inset-inline-start:3px;
      inline-size:16px;block-size:16px;border-radius:50%;background:#fff;
      box-shadow:0 1px 2px rgba(16,24,40,.2);
      transition:transform var(--m-swap) var(--m-ease)}
.ds6 .m-sw[aria-checked="true"]{background:var(--m-ac)}
.ds6 .m-sw[aria-checked="true"]::after{transform:translateX(-16px)}
.ds6 .m-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:var(--m-3)}
@media (max-width:1100px){.ds6 .m-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media (max-width:560px){.ds6 .m-kpis{grid-template-columns:1fr}}
.ds6 /* ====================================================== ASTRA
   The revenue-first Home and the vocabulary it needs. Merged INTO
   this file, .ds6 not layered over it: a second stylesheet that only
   overrides is how revamp.ts got 39 card classes it could never
   reconcile. One rule per selector, .ds6 here, .ds6 or nowhere. */

.m-h1, .ds6 .m-greet__t{
  margin-block: 0;
  font-size: var(--m-t-display);
  line-height: var(--m-leading-title);
  font-weight: 700;
  letter-spacing: 0;
  color: var(--m-ink);
}
.ds6 .m-h2, .ds6 .m-card__t{
  margin-block: 0;
  font-size: var(--m-t-h);
  line-height: var(--m-leading-section);
  font-weight: 700;
  letter-spacing: 0;
  color: var(--m-ink);
}
.ds6 .m-body, .ds6 .m-label{
  margin-block: 0;
  font-size: var(--m-t-body);
  line-height: var(--m-leading-body);
  letter-spacing: 0;
}
.ds6 .m-meta, .ds6 .m-cap, .ds6 .m-stat__s, .ds6 .m-item__s, .ds6 .m-q__s, .ds6 .m-hint{
  margin-block: 0;
  font-size: var(--m-t-cap);
  line-height: var(--m-leading-meta);
  letter-spacing: 0;
  color: var(--m-mut);
}
.ds6 .m-stat__v, .ds6 .m-q__v{
  font-size: var(--m-t-fig);
  line-height: var(--m-leading-figure);
  font-weight: 700;
  letter-spacing: 0;
  color: var(--m-ink);
}
.ds6 .m-stat__v .m-n, .ds6 .m-q__v .m-n{
  letter-spacing: var(--m-tracking-figure);
}
.ds6 .m-q__v.nil, .ds6 .m-stat--mut .m-stat__v{
  color: var(--m-ink);
}
.ds6 .m-side__w, .ds6 .m-nav span{
  transition: opacity var(--m-in) var(--m-ease);
  transform: none;
}
.ds6 .m-side[data-collapsed] .m-side__w, .ds6 .m-side[data-collapsed] .m-nav span{
  transform: none;
  transition: opacity var(--m-out) var(--m-ease);
}
.ds6 body[data-nav="home"] .m-bar{ display: none; }
.ds6 .m-card--pad0, .ds6 .m-card--ledger{
  padding-inline: 0;
  padding-block: 0;
}
.ds6 .m-card--revenue{
  display: grid;
  grid-template-columns: minmax(0, 1.15fr) minmax(0, 1fr);
  gap: var(--m-6);
  padding-inline: var(--m-6);
  padding-block: var(--m-6);
  border-radius: var(--m-r-band);
  box-shadow: var(--m-soft);
}
.ds6 .m-home{
  display: grid;
  gap: var(--m-6);
}
.ds6 .m-home__head{
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: var(--m-2) var(--m-5);
}
.ds6 .m-revenue__main{ min-inline-size: 0; }
.ds6 .m-revenue__value{
  display: flex;
  align-items: baseline;
  gap: var(--m-3);
  margin-block: var(--m-2);
  color: var(--m-ink);
}
.ds6 .m-revenue__value > .m-n{
  font-size: var(--m-t-hero);
  line-height: var(--m-leading-hero);
  font-weight: 700;
  letter-spacing: var(--m-tracking-hero);
}
.ds6 .m-revenue__value > :not(.m-n){
  font-size: 20px;
  line-height: 32px;
  font-weight: 500;
  letter-spacing: 0;
  color: var(--m-mut);
}
.ds6 .m-revenue__context{
  min-inline-size: 0;
  padding-inline-start: var(--m-6);
  border-inline-start: 1px solid var(--m-line);
}
.ds6 .m-facts{
  display: grid;
  gap: var(--m-5);
  margin-block: 0;
}
.ds6 .m-facts dt{
  font-size: 13px;
  line-height: 22px;
  color: var(--m-mut);
}
.ds6 .m-facts dd{
  margin-inline: 0;
  margin-block: var(--m-1) 0;
  font-size: 13px;
  line-height: 22px;
}
.ds6 .m-facts .m-facts__value{
  font-size: 20px;
  line-height: 32px;
  font-weight: 600;
  color: var(--m-ink);
}
.ds6 .m-revenue__qualification{
  margin-block: var(--m-5) var(--m-2);
  font-size: 15px;
  line-height: 26px;
  color: var(--m-ink);
}
.ds6 .m-actions{
  display: flex;
  flex-wrap: wrap;
  gap: var(--m-2);
  margin-block-start: var(--m-5);
}
.ds6 .m-home__work{
  display: grid;
  grid-template-columns: minmax(0, 1fr) 280px;
  gap: var(--m-6);
  align-items: start;
}
.ds6 .m-section-head{
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: var(--m-4);
  flex-wrap: wrap;
  padding-inline: var(--m-5);
  padding-block: var(--m-5) var(--m-4);
}
.ds6 .m-section-head__t{ display: grid; gap: var(--m-1); min-inline-size: 0; }
.ds6 .m-home__decisions{
  min-inline-size: 0;
  padding-block-start: var(--m-2);
  /* The host page styles some bare tags -- its navigation rail is a bare aside element. A
     ported screen must not inherit a colour from whatever tag it happens to use, so this
     states its own ground and ink rather than trusting the cascade to leave it alone. */
  background: transparent;
  color: var(--m-ink-2);
}
.ds6 .m-decision{
  display: grid;
  gap: var(--m-2);
  padding-block: var(--m-4);
  border-block-end: 1px solid var(--m-line);
}
.ds6 .m-decision:last-child{ border-block-end: 0; }
.ds6 .m-decision__title{
  margin-block: 0;
  font-size: 15px;
  line-height: 26px;
  font-weight: 600;
  color: var(--m-ink);
}
.ds6 .m-ledger{ min-inline-size: 560px; }
.ds6 .m-ledger .m-item__s{
  margin-block-start: 2px;
  font-size: 13px;
  line-height: 20px;
}
.ds6 .m-table td.m-td-v, .ds6 .m-table th.num{
  text-align: end;
  color: var(--m-ink);
}
.ds6 .m-table td.m-td-n{
  font-weight: 600;
  color: var(--m-ink);
}
.ds6 .m-ledger__unpriced{
  color: var(--m-warn);
  font-size: 13px;
  line-height: 22px;
  white-space: nowrap;
}
.ds6 #priced-line{ scroll-margin-block-start: var(--m-5); }
.ds6 #priced-line:target{ background: var(--m-ac-dim); }
.ds6 .m-chip, .ds6 .m-status{
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding-inline: 10px;
  padding-block: 3px;
  min-block-size: 28px;
  border-radius: var(--m-r-chip);
  background: var(--m-idle-dim);
  color: var(--m-idle);
  font-size: 13px;
  line-height: 22px;
  font-weight: 500;
  letter-spacing: 0;
  white-space: normal;
}
.ds6 .m-status{ margin-block: var(--m-4) 0; }
.ds6 .m-chip::before, .ds6 .m-status::before{
  content: "";
  inline-size: 6px;
  block-size: 6px;
  flex: 0 0 auto;
  border-radius: 50%;
  background: currentColor;
}
.ds6 .m-status--warn, .ds6 .m-chip--warn{
  background: var(--m-warn-dim);
  color: var(--m-warn);
}
.ds6 .m-input, .ds6 .m-select{
  min-block-size: 44px;
  font-size: 15px;
  line-height: 24px;
  transition: box-shadow var(--m-out) var(--m-ease);
}
.ds6 :where(a, .ds6 button, .ds6 input, .ds6 select, .ds6 textarea, .ds6 summary):focus-visible{
  outline: 2px solid var(--m-ac);
  outline-offset: 3px;
}
.ds6 .m-btn:focus-visible, .ds6 .m-nav:focus-visible, .ds6 .m-tab:focus-visible, .ds6 .m-input:focus-visible, .ds6 .m-select:focus-visible, .ds6 .m-range input:focus-visible{
  outline: 2px solid var(--m-ac);
  outline-offset: 3px;
}
.ds6 .m-btn:not(:disabled):active, .ds6 .m-nav:active, .ds6 .m-side__t:active, .ds6 .m-seg button:active, .ds6 .m-x:active{
  transform: scale(.97);
}
.ds6 .m-btn:disabled:active{ transform: none; }
@media (hover: hover) and (pointer: fine){.ds6 .m-btn:not(:disabled):hover{ background: var(--m-page); }.ds6 .m-btn--primary:not(:disabled):hover{
    background: var(--m-ac-deep);
  }.ds6 .m-table tbody tr:hover{ background: #F8FAF8; }.ds6 .m-link:hover{ color: var(--m-ac); }}
.ds6 .m-evidence{
  border-block-start: 1px solid var(--m-line-2);
}
.ds6 .m-evidence > summary{
  padding-block: var(--m-4);
  cursor: pointer;
  min-block-size: 44px;
}
.ds6 .m-evidence > summary .m-meta{
  display: block;
  margin-block-start: var(--m-1);
}
.ds6 .m-evidence__row{
  display: grid;
  grid-template-columns: minmax(0, 1fr) 220px;
  gap: var(--m-4);
  align-items: start;
  padding-block: var(--m-4);
  border-block-start: 1px solid var(--m-line);
}
.ds6 .m-evidence__row > *{ margin-block: 0; }
.ds6 .m-chart__grow, .ds6 .m-arc__fill, .ds6 .m-fstep__b i{
  animation: none;
}
.ds6 .m-fstep__b i, .ds6 .m-meter i{
  background: var(--m-ac);
}
.ds6 .m-view__p, .ds6 .m-view__p[data-enter]{
  opacity: 1;
  transform: none;
  filter: none;
  transition: none;
}
.ds6 .m-input, .ds6 .m-select, .ds6 .m-tip2, .ds6 .m-table tbody tr, .ds6 .m-th-sort svg, .ds6 .m-cb{
  transition-timing-function: var(--m-ease);
}
.ds6 dialog.m-dlg[data-closing] .m-dlg__p{
  animation: m-dialog-exit var(--m-out) var(--m-ease) both;
}
.ds6 dialog.m-dlg[data-closing]::backdrop{
  animation: m-fade var(--m-out) var(--m-ease) reverse both;
}
@keyframes m-dialog-enter{
  from { opacity: 0; transform: scale(.97); }
  to { opacity: 1; transform: scale(1); }
}
@keyframes m-dialog-exit{
  from { opacity: 1; transform: scale(1); }
  to { opacity: 0; transform: scale(.97); }
}
@media (max-width: 1200px){.ds6 .m-home__work{ grid-template-columns: minmax(0, 1fr); }}
@media (max-width: 900px){.ds6 .m-shell{ display: block; }.ds6 .m-side, .ds6 .m-side[data-collapsed]{
    position: static;
    inline-size: 100%;
    block-size: auto;
    transform: none;
    overflow: visible;
    border-inline-end: 0;
    border-block-end: 1px solid var(--m-line);
    transition: none;
  }.ds6 .m-side__b, .ds6 .m-side__f{ display: none; }.ds6 .m-side__nav{
    display: flex;
    overflow: auto;
    padding-inline: var(--m-4);
    padding-block: var(--m-2);
  }.ds6 .m-nav{ flex: 0 0 auto; }.ds6 .m-side[data-collapsed] .m-nav span, .ds6 .m-side[data-collapsed] .m-nav b{
    opacity: 1;
    transform: none;
  }.ds6 .m-page, .ds6 .m-bar{ padding-inline: var(--m-4); }}
@media (max-width: 700px){.ds6{
    --m-t-hero: 56px;
    --m-leading-hero: 64px;
  }.ds6 .m-home{ gap: var(--m-5); }.ds6 .m-card--revenue{
    grid-template-columns: minmax(0, 1fr);
    gap: var(--m-5);
    padding-inline: var(--m-5);
    padding-block: var(--m-5);
  }.ds6 .m-revenue__context{
    padding-inline-start: 0;
    padding-block-start: var(--m-5);
    border-inline-start: 0;
    border-block-start: 1px solid var(--m-line);
  }.ds6 .m-evidence__row{
    grid-template-columns: minmax(0, 1fr);
    gap: var(--m-2);
  }.ds6 .m-input, .ds6 .m-select{ font-size: 16px; }}
@media (prefers-reduced-motion: reduce){.ds6 *, .ds6 *::before, .ds6 *::after{
    animation: none !important;
    transition: none !important;
    scroll-behavior: auto !important;
  }.ds6 .m-btn:active, .ds6 .m-nav:active, .ds6 .m-side__t:active, .ds6 .m-seg button:active, .ds6 .m-x:active{
    transform: none;
  }}
.ds6 /* The aging rail. One bar per open line, .ds6 length is days without movement —
   the same six numbers the table prints, .ds6 drawn. Nothing is averaged into a
   rate, .ds6 so switching the view cannot change what the page claims. The one
   priced line is the only bar that carries the accent; colour means "this
   one has a number attached", .ds6 not "this one is healthy". */
.m-aging{
  display: grid;
  gap: var(--m-2);
  padding: 0 var(--m-5) var(--m-5);
}
.ds6 .m-aging__r{
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 2fr) auto;
  align-items: center;
  gap: var(--m-3);
}
.ds6 .m-aging__k{
  font-size: var(--m-t-cap);
  color: var(--m-ink-2);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.ds6 .m-aging__b{
  block-size: 10px;
  border-radius: 999px;
  background: var(--m-sunk);
  overflow: hidden;
}
.ds6 .m-aging__b i{
  display: block;
  block-size: 100%;
  inline-size: var(--m-pct, 0%);
  border-radius: 999px;
  background: var(--m-line-2);
  transition: inline-size var(--m-in) var(--m-move);
}
.ds6 .m-aging__b i.is-priced{ background: var(--m-ac); }
.ds6 .m-aging__v{
  font-size: var(--m-t-cap);
  color: var(--m-mut);
  white-space: nowrap;
}
@media (prefers-reduced-motion: reduce){.ds6 .m-aging__b i{ transition: none; }}
@media (max-width: 720px){.ds6 .m-aging__r{ grid-template-columns: minmax(0, 1fr) auto; }.ds6 .m-aging__b{ grid-column: 1 / -1; }}
.ds6 /* The outgoing half of a view swap. Same visual state as [data-enter] — a
   crossfade has two sides and they must be symmetric, .ds6 or the swap reads as
   one panel shoving another out of the way. */
.m-view__p[data-away]{
  opacity: 0;
  transform: translateY(6px);
  filter: blur(3px);
}
@media (prefers-reduced-motion: reduce){.ds6 .m-view__p[data-away]{ transform: none; filter: none; }}
.ds6 .m-home__dateline{ margin-block: calc(-1 * var(--m-3)) var(--m-4); }
.ds6 /* The readiness meter is one figure among four rows of plain sentences; at
   full column width it reads as the panel's subject rather than one line in
   it. Cap it, .ds6 and let every row's figure column align to the same edge. */
.m-evidence__row > * + *{ text-align: end; }
@media (max-width: 720px){.ds6 .m-evidence__row{ grid-template-columns: minmax(0, 1fr); }.ds6 .m-evidence__row > * + *{ text-align: start; }}
.ds6 .m-chip{ white-space: nowrap; }
`;
